// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Permissions } from "./Permissions";

export interface PermissionsListResponse { permissions: Array<Permissions>, count: bigint, }